# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FjACVeEghCc4tqA1nKyMYTey-BWgwVvk
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

data=pd.read_csv('user_behavior_dataset.csv')
data.head(10)

data.info()

data.describe()

data.isnull().sum()

data.shape

"""**Exploratory Data Analysis (EDA) & Visualizations**

**1 App Usage Time vs. Battery Drain**

**Insight Goal: Are users with high app usage consuming more battery power?**
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(x='App Usage Time (min/day)', y='Battery Drain (mAh/day)', data=data)
plt.title('App Usage Time vs Battery Drain')
plt.xlabel('App Usage Time (min/day)')
plt.ylabel('Battery Drain (mAh/day)')
plt.show()

correlation = data['App Usage Time (min/day)'].corr(data['Battery Drain (mAh/day)'])
print(f'Correlation: {correlation:.2f}')

"""**2 Average Screen-On Time by Gender**

**Do male and female users differ in screen-on time?**
"""

plt.figure(figsize=(8, 6))
sns.barplot(x='Gender', y='Screen On Time (hours/day)', data=data, ci=None)
plt.title('Average Screen-On Time by Gender')
plt.show()

"""**3. What is the Average Screen-On Time by Age Group?**

Insight Goal: Are younger users spending more time on their screens?
"""

bins = [0, 18, 25, 35, 45, 55, 65, 100]
labels = ['0-17', '18-24', '25-34', '35-44', '45-54', '55-64', '65+']
data['Age Group'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)


avg_screen_time = data.groupby('Age Group')['Screen On Time (hours/day)'].mean()
print(avg_screen_time)

avg_screen_time.plot(kind='bar',  figsize=(8, 5))
plt.title('Average Screen-On Time by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Screen On Time (hours/day)')
plt.show()

"""**4. How Does the Number of Installed Apps Relate to Data Usage?**

**Insight Goal: Does installing more apps lead to higher data consumption?**
"""

plt.figure(figsize=(8, 5))
sns.scatterplot(x='Number of Apps Installed', y='Data Usage (MB/day)', data=data)
plt.title('Number of Apps Installed vs Data Usage')
plt.xlabel('Number of Apps Installed')
plt.ylabel('Data Usage (MB/day)')
plt.show()

correlation_apps_data = data['Number of Apps Installed'].corr(data['Data Usage (MB/day)'])
print(f'Correlation: {correlation_apps_data:.2f}')

"""**5. Average Battery Drain by Operating System**

**Insight Goal: Identify which OS struggles more with battery life.**
"""

avg_battery_drain_os = data.groupby('Operating System')['Battery Drain (mAh/day)'].mean()
print(avg_battery_drain_os)


avg_battery_drain_os.plot(kind='bar', color='coral', figsize=(8, 5))
plt.title('Average Battery Drain by Operating System')
plt.xlabel('Operating System')
plt.ylabel('Battery Drain (mAh/day)')
plt.show()

"""**6. How Does Gender Affect App Usage Time?**

**Insight Goal: Compare app usage time between males and females.**
"""

avg_app_usage_gender = data.groupby('Gender')['App Usage Time (min/day)'].mean()
print(avg_app_usage_gender)


avg_app_usage_gender.plot(kind='bar', color=['blue', 'orange'], figsize=(8, 5))
plt.title('Average App Usage Time by Gender')
plt.xlabel('Gender')
plt.ylabel('App Usage Time (min/day)')
plt.xticks(rotation=0)
plt.show()

"""**7. Distribution of User Behavior Classes**

**Insight Goal: Understand the proportion of users in each behavior category.**
"""

behavior_count = data['User Behavior Class'].value_counts()
print(behavior_count)


behavior_count.plot(kind='pie', autopct='%1.1f%%', colors=['gold', 'lightblue', 'lightgreen'], figsize=(8, 5))
plt.title('Distribution of User Behavior Classes')
plt.ylabel('')
plt.show()